# Generated by Django 4.1.7 on 2023-03-15 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_code', models.CharField(max_length=8)),
                ('category_type', models.CharField(max_length=20)),
                ('category_level', models.CharField(max_length=50)),
                ('players_type', models.CharField(max_length=10)),
                ('players_value', models.IntegerField(default=1)),
                ('miscellaneous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=200)),
                ('game_abbreviation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SrdcUser',
            fields=[
                ('srdc_user', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('srdc_user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameAliases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_alias', models.CharField(max_length=50, unique=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.game')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAliases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_alias', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.game'),
        ),
        migrations.CreateModel(
            name='VariableFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_code', models.CharField(max_length=8)),
                ('variable_name', models.CharField(max_length=100)),
                ('variable_value', models.CharField(max_length=8)),
                ('variable_value_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.category')),
            ],
            options={
                'unique_together': {('variable_code', 'category')},
            },
        ),
    ]
